name: Second workflow
on:
  push:
  workflow_dispatch:
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: "welcomme"
        run: echo "Welcome to the code step by step"

  bye-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Bye"
        run: echo "Bye to the code step by step"
